[package]
name = "custom-id"
version = "0.1.0"
edition = "2021"

[lib]
name = "custom_id"
path = "src/lib.rs"

[dependencies]
bitvec = "1.0.1"
custom-id-macro = { path = "custom-id-macro" }
thiserror = "2.0.2"

twilight-model = "=0.16.0-rc.1"
